#last updated: 11-02-2023 07:20am
system:
  host-name: SiteA-Router

interfaces:
  ethernet:
  - name: eth0
    address: 172.16.1.2/24
    description: SiteA_Central
  - name: eth1
    address: 172.16.100.3/24
    description: Router_Managment
  - name: eth2
    address: 10.1.0.1/24
    description: SiteA_Subnet1
  - name: eth3
    address: 10.1.1.1/24
    description: SiteA_Subnet2


protocols:
  static:
    route:
    - network: 0.0.0.0/0
      next-hop: 172.16.1.1

nat:
  source:
    rules:
    - rule_id: "10"
      destination: 10.2.0.0/23
      exclude: true
      outbound-interface: eth0
      source: 10.1.0.0/23

vpn:
  ipsec:
    esp-group:
    - name: site-a-srv-esp
      compression: disable
      lifetime: "1800"
      mode: tunnel
      pfs: enable
      proposal_id: "1"
      encryption: aes256
      hash: sha1
    ike-group:
    - name: site-a-srv-ike
      ikev2-reauth: "no"
      key-exchange: ikev1
      lifetime: "3600"
      proposal_id: "1"
      encryption: aes256
      hash: sha1
    interface: eth0
    site-to-site: 
      peer:
      - name: 172.16.1.1
        authentication:
          mode: pre-shared-secret
          pre-shared-secret: swisscom
          remote-id: 172.16.1.1
        ike-group: site-a-srv-ike
        local-address: 172.16.1.2
        remote-address: 172.16.1.1
        tunnel:
        - tunnel_id: "0"
          esp-group: site-a-srv-esp
          local-prefix: 10.1.0.0/23
          remote-prefix: 10.2.0.0/23


firewall:
  interface:
  - name: eth2
    in_name: Subnet1A_IN
    out_name: ""
  - name: eth3
    in_name: Subnet2A_IN
    out_name: ""
  rules:
  - name: Subnet1A_IN
    default-action: accept
    rule_id: "1"
    action: drop
    destination: 10.2.1.0/24
    source: 10.1.0.0/24
  - name: Subnet2A_IN
    default-action: accept
    rule_id: "2"
    action: drop
    destination: 10.2.0.0/24
    source: 10.1.1.0/24
